Parameters:
  InstanceType:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ec2/instanceType

  ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: demo-key-pair

Resources:
  CFTInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      ImageId: !Ref ImageId
      SubnetId: !ImportValue PublicSubnet
      SecurityGroupIds:
        - !ImportValue SSHSecurityGroup

Outputs:
  EC2PublicIp:
    Description: Public Ip Address of EC2 instance
    Value: !GetAtt CFTInstance.PublicIp
    Export:
      Name: EC2PublicIp
